GET http://localhost:3002/api/v1/users

### create post
POST http://localhost:3002/api/v1/users
Content-Type: application/json

{
    "username":"james",
    "email":"james@gmail.com",
    "password":"456213"

}

###Create put
PUT http://localhost:3002/api/v1/users/1
Content-Type: application/json

{
  "username": "Taychit",
  "email": "new@gmail.com",
  "password":"234556"
}